version: "2"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8888:80"
    volumes:
     - .:/var/www
    depends_on:
      - db
  db:
    image: mysql
    command: --default-autentication-plugin=mysql_native_password
    container_name: exercicio-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: programadorabordo
    volumes:
      - ./api/db/data:/var/lib/mysql
    restart: always
    ports:
      - "9001:9001"



